// texts.js - all player-facing UI strings. German is the primary language (arcade in Chemnitz),
// English is a fallback map with the same keys. `getTexts(lang)` returns a merged object so that
// a missing English key falls back to German. Pure data, no DOM.

export const de = Object.freeze({
  appName: 'Dancing Points VR',
  // menu
  menuTitle: 'Tanz auswählen',
  menuPlay: 'Tanzen',
  menuDuo: 'Duo-Modus',
  menuRecord: 'Neuen Tanz aufnehmen',
  menuSettings: 'Einstellungen',
  menuHighscores: 'Bestenliste',
  menuOwnDances: 'Eigene Tänze',
  menuShippedDances: 'Tänze',
  menuBack: 'Zurück',
  menuStart: 'Start',
  menuRecalibrate: 'Neu kalibrieren',
  menuVersion: 'Version',
  menuEnterVr: 'VR starten',
  menuVrUnavailable: 'WebXR nicht verfügbar – Desktop-Modus',
  menuDifficulty: 'Schwierigkeit',
  menuDuration: 'Dauer',
  menuBpm: 'BPM',
  menuLoading: 'Lade …',
  menuNoChoreos: 'Keine Tänze gefunden',
  menuPage: 'Seite',
  // settings
  settingsTitle: 'Einstellungen',
  settingsAvatar: 'Avatar',
  settingsAvatarNeural: 'Neural (Ganzkörper)',
  settingsAvatarPoints: 'Punkte',
  settingsAvatarOff: 'Aus',
  settingsAudio: 'Lautstärke',
  settingsServer: 'Server',
  settingsTelemetry: 'Telemetrie',
  settingsTelemetryExport: 'Telemetrie exportieren',
  settingsLanguage: 'Sprache',
  settingsMirror: 'Spiegeln',
  settingsPlayerName: 'Spielername',
  settingsOn: 'An',
  settingsOff: 'Aus',
  // calibration
  calibrateTitle: 'Kalibrierung',
  calibrateInstruction: 'Stell dich auf die Markierung, schau nach vorn zur Bühne und halte den Trigger gedrückt.',
  calibrateInstructionEmu: 'Kalibrierung läuft automatisch …',
  calibrateHold: 'Halten …',
  calibrateDone: 'Kalibriert!',
  calibrateHeight: 'Größe',
  calibrateFailed: 'Kalibrierung fehlgeschlagen – bitte Headset aufsetzen und erneut versuchen.',
  // countdown / play
  countdownReady: 'Bereit?',
  countdownGo: 'Los!',
  hudScore: 'Punkte',
  hudCombo: 'Combo',
  hudMove: 'Move',
  hudNextMove: 'Als Nächstes',
  hudTime: 'Zeit',
  hudPaused: 'Pause',
  hudResume: 'Weiter',
  hudQuit: 'Abbrechen',
  hudTrackingLost: 'Controller nicht sichtbar',
  hudNeuralDisabled: 'Neural-Avatar deaktiviert (zu langsam)',
  hudNeuralLoading: 'Neural-Avatar lädt …',
  // grades
  gradePerfekt: 'Perfekt',
  gradeGut: 'Gut',
  gradeOk: 'OK',
  gradeDaneben: 'Daneben',
  gradeMiss: 'Verpasst',
  // results
  resultsTitle: 'Ergebnis',
  resultsScore: 'Punkte',
  resultsStars: 'Sterne',
  resultsMaxCombo: 'Beste Combo',
  resultsTimingEarly: 'Du warst etwas zu früh',
  resultsTimingLate: 'Du warst etwas zu spät',
  resultsTimingOnBeat: 'Timing im Takt',
  resultsTiming: 'Timing',
  resultsPerMove: 'Bewertung pro Move',
  resultsAgain: 'Nochmal',
  resultsMenu: 'Menü',
  resultsSaved: 'Ergebnis gespeichert',
  resultsSaveFailed: 'Ergebnis konnte nicht an den Server gesendet werden',
  resultsNewHighscore: 'Neuer Rekord!',
  resultsWinner: 'Gewinner',
  resultsDraw: 'Unentschieden',
  resultsSync: 'Synchronität',
  resultsSyncLag: 'Versatz',
  // recorder
  recordTitle: 'Neuen Tanz aufnehmen',
  recordName: 'Titel',
  recordBpm: 'BPM',
  recordTapTempo: 'Tempo tippen',
  recordBars: 'Takte',
  recordCountIn: 'Einzähler',
  recordSynth: 'Beat',
  recordMirror: 'Spiegeln',
  recordAudioUrl: 'Audio-URL (optional)',
  recordStart: 'Aufnahme starten',
  recording: 'Aufnahme läuft …',
  recordReviewTitle: 'Aufnahme prüfen',
  recordPlayback: 'Abspielen',
  recordSave: 'Speichern',
  recordDiscard: 'Verwerfen',
  recordSaved: 'Tanz gespeichert',
  recordSavedLocal: 'Tanz lokal gespeichert (kein Server)',
  recordSaveFailed: 'Speichern fehlgeschlagen',
  recordPartName: 'Teil',
  recordTooShort: 'Aufnahme zu kurz',
  // duo
  duoTitle: 'Duo-Modus',
  duoGhost: 'Gegen Aufzeichnung',
  duoOnline: 'Online (WLAN)',
  duoRoomCode: 'Raumcode',
  duoCreateRoom: 'Raum erstellen',
  duoJoinRoom: 'Raum beitreten',
  duoWaiting: 'Warte auf Mitspieler …',
  duoPlayerJoined: 'Mitspieler beigetreten',
  duoPlayerLeft: 'Mitspieler hat den Raum verlassen',
  duoHostStart: 'Als Host starten',
  duoNoServer: 'Kein Server konfiguriert',
  duoConnectionLost: 'Verbindung zum Server verloren',
  duoNoRuns: 'Keine Aufzeichnung für diesen Tanz vorhanden – spiel ihn zuerst einmal solo.',
  duoYou: 'Du',
  duoGhostName: 'Aufzeichnung',
  duoOpponent: 'Mitspieler',
  duoBenchmark: 'Benchmark',
  duoExportJson: 'JSON exportieren',
  duoExportCsv: 'CSV exportieren',
  // highscores
  highscoresTitle: 'Bestenliste',
  highscoresEmpty: 'Noch keine Ergebnisse',
  highscoresLocal: 'Lokal',
  highscoresServer: 'Server',
  // generic
  ok: 'OK',
  cancel: 'Abbrechen',
  yes: 'Ja',
  no: 'Nein',
  error: 'Fehler',
  loading: 'Lade …',
  offline: 'Offline',
  online: 'Online',
  unknown: 'Unbekannt',
  seconds: 'Sekunden',
  secondsShort: 's',
  player: 'Spieler',
  errorChoreoLoad: 'Tanz konnte nicht geladen werden',
  errorChoreoInvalid: 'Tanzdatei ist ungültig',
  errorAudioLoad: 'Audio konnte nicht geladen werden – Beat wird synthetisch erzeugt',
  errorXr: 'VR-Sitzung konnte nicht gestartet werden',
  errorModelLoad: 'Neuronales Netz konnte nicht geladen werden',
});

export const en = Object.freeze({
  appName: 'Dancing Points VR',
  menuTitle: 'Choose a dance',
  menuPlay: 'Dance',
  menuDuo: 'Duo mode',
  menuRecord: 'Record a new dance',
  menuSettings: 'Settings',
  menuHighscores: 'Highscores',
  menuOwnDances: 'My dances',
  menuShippedDances: 'Dances',
  menuBack: 'Back',
  menuStart: 'Start',
  menuRecalibrate: 'Recalibrate',
  menuVersion: 'Version',
  menuEnterVr: 'Enter VR',
  menuVrUnavailable: 'WebXR not available - desktop mode',
  menuDifficulty: 'Difficulty',
  menuDuration: 'Duration',
  menuBpm: 'BPM',
  menuLoading: 'Loading ...',
  menuNoChoreos: 'No dances found',
  menuPage: 'Page',
  settingsTitle: 'Settings',
  settingsAvatar: 'Avatar',
  settingsAvatarNeural: 'Neural (full body)',
  settingsAvatarPoints: 'Points',
  settingsAvatarOff: 'Off',
  settingsAudio: 'Volume',
  settingsServer: 'Server',
  settingsTelemetry: 'Telemetry',
  settingsTelemetryExport: 'Export telemetry',
  settingsLanguage: 'Language',
  settingsMirror: 'Mirror',
  settingsPlayerName: 'Player name',
  settingsOn: 'On',
  settingsOff: 'Off',
  calibrateTitle: 'Calibration',
  calibrateInstruction: 'Stand on the marker, face the stage and hold the trigger.',
  calibrateInstructionEmu: 'Calibrating automatically ...',
  calibrateHold: 'Hold ...',
  calibrateDone: 'Calibrated!',
  calibrateHeight: 'Height',
  calibrateFailed: 'Calibration failed - put on the headset and try again.',
  countdownReady: 'Ready?',
  countdownGo: 'Go!',
  hudScore: 'Score',
  hudCombo: 'Combo',
  hudMove: 'Move',
  hudNextMove: 'Next',
  hudTime: 'Time',
  hudPaused: 'Paused',
  hudResume: 'Resume',
  hudQuit: 'Quit',
  hudTrackingLost: 'Controllers not visible',
  hudNeuralDisabled: 'Neural avatar disabled (too slow)',
  hudNeuralLoading: 'Neural avatar loading ...',
  gradePerfekt: 'Perfect',
  gradeGut: 'Good',
  gradeOk: 'OK',
  gradeDaneben: 'Miss',
  gradeMiss: 'Missed',
  resultsTitle: 'Result',
  resultsScore: 'Score',
  resultsStars: 'Stars',
  resultsMaxCombo: 'Best combo',
  resultsTimingEarly: 'You were a bit early',
  resultsTimingLate: 'You were a bit late',
  resultsTimingOnBeat: 'Timing on the beat',
  resultsTiming: 'Timing',
  resultsPerMove: 'Score per move',
  resultsAgain: 'Again',
  resultsMenu: 'Menu',
  resultsSaved: 'Result saved',
  resultsSaveFailed: 'Could not send the result to the server',
  resultsNewHighscore: 'New record!',
  resultsWinner: 'Winner',
  resultsDraw: 'Draw',
  resultsSync: 'Sync',
  resultsSyncLag: 'Lag',
  recordTitle: 'Record a new dance',
  recordName: 'Title',
  recordBpm: 'BPM',
  recordTapTempo: 'Tap tempo',
  recordBars: 'Bars',
  recordCountIn: 'Count-in',
  recordSynth: 'Beat',
  recordMirror: 'Mirror',
  recordAudioUrl: 'Audio URL (optional)',
  recordStart: 'Start recording',
  recording: 'Recording ...',
  recordReviewTitle: 'Review recording',
  recordPlayback: 'Play',
  recordSave: 'Save',
  recordDiscard: 'Discard',
  recordSaved: 'Dance saved',
  recordSavedLocal: 'Dance saved locally (no server)',
  recordSaveFailed: 'Saving failed',
  recordPartName: 'Part',
  recordTooShort: 'Recording too short',
  duoTitle: 'Duo mode',
  duoGhost: 'Versus recording',
  duoOnline: 'Online (WLAN)',
  duoRoomCode: 'Room code',
  duoCreateRoom: 'Create room',
  duoJoinRoom: 'Join room',
  duoWaiting: 'Waiting for partner ...',
  duoPlayerJoined: 'Partner joined',
  duoPlayerLeft: 'Partner left the room',
  duoHostStart: 'Start as host',
  duoNoServer: 'No server configured',
  duoConnectionLost: 'Connection to the server lost',
  duoNoRuns: 'No recording for this dance yet - play it solo first.',
  duoYou: 'You',
  duoGhostName: 'Recording',
  duoOpponent: 'Partner',
  duoBenchmark: 'Benchmark',
  duoExportJson: 'Export JSON',
  duoExportCsv: 'Export CSV',
  highscoresTitle: 'Highscores',
  highscoresEmpty: 'No results yet',
  highscoresLocal: 'Local',
  highscoresServer: 'Server',
  ok: 'OK',
  cancel: 'Cancel',
  yes: 'Yes',
  no: 'No',
  error: 'Error',
  loading: 'Loading ...',
  offline: 'Offline',
  online: 'Online',
  unknown: 'Unknown',
  seconds: 'seconds',
  secondsShort: 's',
  player: 'Player',
  errorChoreoLoad: 'Could not load the dance',
  errorChoreoInvalid: 'Dance file is invalid',
  errorAudioLoad: 'Could not load audio - using the synthetic beat',
  errorXr: 'Could not start the VR session',
  errorModelLoad: 'Could not load the neural network',
});

export const LANGUAGES = Object.freeze(['de', 'en']);

/** Grade id (as produced by the Scorer) -> text key. */
export const GRADE_KEYS = Object.freeze({
  perfekt: 'gradePerfekt',
  gut: 'gradeGut',
  ok: 'gradeOk',
  daneben: 'gradeDaneben',
});

/**
 * Return the strings for `lang` ('de' | 'en'); unknown languages and missing keys fall back to
 * German. The returned object is frozen.
 */
export function getTexts(lang = 'de') {
  if (lang === 'en') return Object.freeze({ ...de, ...en });
  return de;
}

/** Convenience lookup with a `{name}` placeholder substitution. */
export function formatText(texts, key, vars = null) {
  let s = texts[key];
  if (s === undefined) s = de[key];
  if (s === undefined) return key;
  if (vars) {
    for (const k of Object.keys(vars)) {
      s = s.split(`{${k}}`).join(String(vars[k]));
    }
  }
  return s;
}
