// pipeline-math.test.js - parity of webxr/src/net/pipeline.js primitives with tests/fixtures/math.json
// (generated by tools/gen_fixtures.py from the numpy oracle tools/dp_pipeline.py). node --test.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import * as P from '../../webxr/src/net/pipeline.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(join(here, '..', 'fixtures', 'math.json'), 'utf8'));

const TOL = 2e-6; // fixture values are float32 rounded to 7 significant digits (~1e-7 relative)
const stats = new Map(); // kind -> max abs error (reported at the end)

function note(kind, err) {
  stats.set(kind, Math.max(stats.get(kind) || 0, err));
}

function maxAbsDiff(a, b) {
  const fa = [];
  const fb = [];
  P.flattenInto(fa, Array.isArray(a) ? a : Array.from(a));
  P.flattenInto(fb, Array.isArray(b) ? b : Array.from(b));
  assert.equal(fa.length, fb.length, 'length mismatch');
  let m = 0;
  for (let i = 0; i < fa.length; i++) {
    assert.ok(Number.isFinite(fa[i]), 'non-finite value');
    m = Math.max(m, Math.abs(fa[i] - fb[i]));
  }
  return m;
}

function expectNear(kind, got, exp, label, tol = TOL) {
  const err = maxAbsDiff(got, exp);
  note(kind, err);
  assert.ok(err <= tol, `${label}: max abs error ${err} > ${tol}`);
}

const byKind = (kind) => fixture.cases.filter((c) => c.kind === kind);

test('fixture format', () => {
  assert.equal(fixture.format, 'dancing-points-fixture/1');
  assert.equal(fixture.kind, 'math');
  assert.ok(fixture.cases.length >= 39);
});

test('rootFromHead: forward, root position, yaw (with prevYaw fallback), rm, matrix', () => {
  const cases = byKind('rootFromHead');
  assert.equal(cases.length, 11);
  const fwd = new Float64Array(3);
  const pos = new Float64Array(3);
  const rm = new Float64Array(4);
  const m = new Float64Array(16);
  for (const c of cases) {
    const { headPos, headQuat, prevYaw } = c.input;
    P.headForward(fwd, 0, headQuat, 0);
    expectNear('rootFromHead', fwd, c.expected.forward, `${c.id} forward`);
    const yaw = P.rootFromHead(pos, 0, headPos, 0, fwd, 0, prevYaw);
    expectNear('rootFromHead', pos, c.expected.rootPos, `${c.id} rootPos`);
    expectNear('rootFromHead', [yaw], [c.expected.yaw], `${c.id} yaw`);
    if (c.note.includes('prevYaw')) assert.equal(yaw, prevYaw, `${c.id}: degenerate forward must keep prevYaw exactly`);
    P.rmFromRoot(rm, 0, pos[0], pos[2], yaw);
    expectNear('rootFromHead', rm, c.expected.rm, `${c.id} rm`);
    P.rootMatrix(m, 0, pos[0], pos[1], pos[2], yaw);
    expectNear('rootFromHead', m, c.expected.matrix, `${c.id} matrix`);
    if (c.expected.datasetRm) expectNear('rootFromHead', rm, c.expected.datasetRm, `${c.id} datasetRm`, 1e-5);
  }
});

test('rmMatrix: rm -> matrix -> rm round trip, yaw, pos', () => {
  const cases = byKind('rmMatrix');
  assert.equal(cases.length, 6);
  const m = new Float64Array(16);
  const rm = new Float64Array(4);
  for (const c of cases) {
    P.rmToMatrix(m, 0, c.input.rm, 0);
    expectNear('rmMatrix', m, c.expected.matrix, `${c.id} matrix`);
    expectNear('rmMatrix', [P.rmYaw(c.input.rm, 0)], [c.expected.yaw], `${c.id} yaw`);
    expectNear('rmMatrix', [c.input.rm[2], 0, c.input.rm[3]], c.expected.pos, `${c.id} pos`);
    P.rmFromMatrix(rm, 0, c.expected.matrix, 0);
    expectNear('rmMatrix', rm, c.expected.rmFromMatrix, `${c.id} rmFromMatrix`);
  }
});

test('rmRelative / rmApply: complex-plane relative root and its inverse', () => {
  const cases = byKind('rmRelative');
  assert.equal(cases.length, 6);
  const rel = new Float64Array(4);
  const m = new Float64Array(16);
  const applied = new Float64Array(4);
  const self = new Float64Array(4);
  for (const c of cases) {
    P.rmRelative(rel, 0, c.input.rm, 0, c.input.ref, 0);
    expectNear('rmRelative', rel, c.expected.rel, `${c.id} rel`);
    P.rmToMatrix(m, 0, rel, 0);
    expectNear('rmRelative', m, c.expected.relMatrix, `${c.id} relMatrix`);
    P.rmApply(applied, 0, c.input.ref, 0, c.expected.rel, 0);
    expectNear('rmRelative', applied, c.expected.applied, `${c.id} applied`);
    P.rmRelative(self, 0, c.input.ref, 0, c.input.ref, 0);
    expectNear('rmRelative', self, c.expected.selfRelative, `${c.id} selfRelative`);
    // exactly the identity (=== treats -0 as 0)
    assert.ok(self[0] === 1 && self[1] === 0 && self[2] === 0 && self[3] === 0, `${c.id}: relative to itself must be exactly [1,0,0,0], got ${Array.from(self)}`);
  }
});

test('localWorld: M^-1 p and M p', () => {
  const cases = byKind('localWorld');
  assert.equal(cases.length, 4);
  const m = new Float64Array(16);
  const local = new Float64Array(9);
  const back = new Float64Array(9);
  for (const c of cases) {
    P.rmToMatrix(m, 0, c.input.rm, 0);
    const world = new Float64Array(9);
    P.flattenInto(world, c.input.world);
    const expLocal = new Float64Array(9);
    P.flattenInto(expLocal, c.expected.local);
    for (let k = 0; k < 3; k++) {
      P.toLocal(local, k * 3, m, 0, world, k * 3);
      P.toWorld(back, k * 3, m, 0, expLocal, k * 3);
    }
    expectNear('localWorld', local, c.expected.local, `${c.id} local`);
    expectNear('localWorld', back, c.expected.worldBack, `${c.id} worldBack`);
    // aliasing: out may be the input
    const alias = Float64Array.from(world);
    for (let k = 0; k < 3; k++) P.toLocal(alias, k * 3, m, 0, alias, k * 3);
    expectNear('localWorld', alias, c.expected.local, `${c.id} local (aliased)`);
  }
});

test('dpToS / sToDp: positions, quaternions, rotation = M R M, forward', () => {
  const dp = byKind('dpToS');
  const sd = byKind('sToDp');
  assert.equal(dp.length, 5);
  assert.equal(sd.length, 3);
  const p = new Float64Array(3);
  const q = new Float64Array(4);
  const r = new Float64Array(9);
  const rDP = new Float64Array(9);
  const fwd = new Float64Array(3);
  const mirrorRot = (out, rr) => { // M R M with M = diag(1, 1, -1): negate entries with exactly one z index
    for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) out[i * 3 + j] = rr[i * 3 + j] * (((i === 2) !== (j === 2)) ? -1 : 1);
    return out;
  };
  const mrm = new Float64Array(9);
  for (const c of dp) {
    P.dpToSPos(p, 0, c.input.posDP, 0);
    expectNear('dpToS', p, c.expected.posS, `${c.id} posS`);
    P.dpToSQuat(q, 0, c.input.quatDP, 0);
    expectNear('dpToS', q, c.expected.quatS, `${c.id} quatS`);
    P.quatToMat(r, 0, q, 0);
    expectNear('dpToS', r, c.expected.rotS, `${c.id} rotS (quatToMat(quatS))`);
    P.quatToMat(rDP, 0, c.input.quatDP, 0);
    expectNear('dpToS', mirrorRot(mrm, rDP), c.expected.rotS, `${c.id} rotS (M R M)`);
    P.headForward(fwd, 0, c.input.quatDP, 0);
    expectNear('dpToS', fwd, c.expected.forwardDP, `${c.id} forwardDP`);
    // forwardS = quatS * (0,0,-1) = -(third column of R_S)
    expectNear('dpToS', [-r[2], -r[5], -r[8]], c.expected.forwardS, `${c.id} forwardS`);
    P.dpToSPos(fwd, 0, fwd, 0);
    expectNear('dpToS', fwd, c.expected.forwardS, `${c.id} forwardS = dpToS(forwardDP)`);
  }
  for (const c of sd) {
    P.sToDpPos(p, 0, c.input.posS, 0);
    expectNear('sToDp', p, c.expected.posDP, `${c.id} posDP`);
    P.sToDpQuat(q, 0, c.input.quatS, 0);
    expectNear('sToDp', q, c.expected.quatDP, `${c.id} quatDP`);
    P.quatToMat(r, 0, q, 0);
    expectNear('sToDp', r, c.expected.rotDP, `${c.id} rotDP`);
  }
  // involution on a full frame
  const frame = new Float64Array(13);
  for (let i = 0; i < 13; i++) frame[i] = Math.sin(i + 1);
  const conv = new Float64Array(13);
  P.frameDpToS(conv, 0, frame, 0);
  P.frameSToDp(conv, 0, conv, 0);
  assert.deepEqual(Array.from(conv), Array.from(frame));
});

test('headForward and quatToMat', () => {
  const cases = byKind('headForward');
  assert.equal(cases.length, 3);
  const fwd = new Float64Array(3);
  const r = new Float64Array(9);
  const v = new Float64Array(3);
  for (const c of cases) {
    P.headForward(fwd, 0, c.input.quatDP, 0);
    expectNear('headForward', fwd, c.expected.forwardDP, `${c.id} forwardDP`);
    P.quatToMat(r, 0, c.input.quatDP, 0);
    expectNear('headForward', r, c.expected.rot, `${c.id} rot`);
    P.quatRotate(v, 0, c.input.quatDP, 0, [0, 0, 1], 0);
    expectNear('headForward', v, c.expected.forwardDP, `${c.id} quatRotate(0,0,1)`);
  }
});

test('frameRoots over a sequence with a degenerate frame + threePointLocal', () => {
  const cases = byKind('frameRoots');
  assert.equal(cases.length, 1);
  const c = cases[0];
  const T = c.input.frames.length;
  const frames = new Float64Array(T * P.FRAME_DIM);
  P.flattenInto(frames, c.input.frames);
  const pos = new Float64Array(T * 3);
  const yaw = new Float64Array(T);
  P.frameRoots(frames, T, c.input.prevYaw, pos, yaw, new Float64Array(3));
  expectNear('frameRoots', pos, c.expected.rootPos, `${c.id} rootPos`);
  expectNear('frameRoots', yaw, c.expected.yaw, `${c.id} yaw`);
  assert.equal(yaw[3], yaw[2], 'degenerate frame 3 keeps the yaw of frame 2 exactly');
  const rm = new Float64Array(T * 4);
  for (let i = 0; i < T; i++) P.rmFromRoot(rm, i * 4, pos[i * 3], pos[i * 3 + 2], yaw[i]);
  expectNear('frameRoots', rm, c.expected.rm, `${c.id} rm`);
  const local = new Float64Array(T * 9);
  P.threePointLocal(frames, T, pos, yaw, local, new Float64Array(4), new Float64Array(16));
  expectNear('frameRoots', local, c.expected.local, `${c.id} local`);
  // head local x/z are exactly 0 by construction (=== accepts -0)
  for (let i = 0; i < T; i++) {
    assert.ok(local[i * 9] === 0 && local[i * 9 + 2] === 0, `head local xz of frame ${i} must be 0`);
  }
});

test('wrapAngle matches Python (a + pi) % (2 pi) - pi', () => {
  assert.ok(Math.abs(P.wrapAngle(3 * Math.PI) - (-Math.PI)) < 1e-12 || Math.abs(P.wrapAngle(3 * Math.PI) - Math.PI) < 1e-12);
  assert.ok(Math.abs(P.wrapAngle(Math.PI + 0.1) - (-Math.PI + 0.1)) < 1e-12);
  assert.ok(Math.abs(P.wrapAngle(-Math.PI - 0.1) - (Math.PI - 0.1)) < 1e-12);
  assert.equal(P.wrapAngle(0.5), 0.5);
  assert.ok(Math.abs(P.wrapAngle(-7) - (-7 + 2 * Math.PI)) < 1e-12);
});

test('channelMajor / splitFrame layout', () => {
  const x = new Float64Array([1, 2, 3, 4, 5, 6]); // T=2, C=3
  const out = new Float64Array(6);
  P.channelMajor(out, x, 2, 3);
  assert.deepEqual(Array.from(out), [1, 4, 2, 5, 3, 6]);
  const f = new Float64Array(3);
  P.splitFrame(f, out, 2, 3, 1);
  assert.deepEqual(Array.from(f), [4, 5, 6]);
});

test('report achieved tolerances', () => {
  const lines = [];
  for (const [k, v] of stats) lines.push(`${k}: ${v.toExponential(2)}`);
  console.log('math.json max abs errors -> ' + lines.join(', '));
  for (const [k, v] of stats) assert.ok(v <= TOL, `${k} ${v}`);
});
